### ISSUE TITLE
Error description not shown

### ISSUE THREAD

**Issue by citizen-seven** [enqueue/metabase-clickhouse-driver#53] opened 2020-05-28 08:26 UTC
Clickhouse driver in python clearly explains error with description. It's inconvenient to copy query, insert into python script to see where error is.

Current error description looks like this:
```  
ClickHouse exception, code: 403, host: HOST, port: PORT
```

What I see in python-clickhousedriver:
```
ServerException: Code: 403.
DB::Exception: Invalid expression for JOIN ON. In expression `--o.ship_address_id` = `--o.id` columns `--o.ship_address_id` and `--o.id` are from the same table but from different arguments of equal function. Supported syntax: JOIN ON Expr([table.]column, ...) = Expr([table.]column, ...) [AND Expr([table.]column, ...) = Expr([table.]column, ...) ...]. 
```

Any way to fix this?

**Comment by enqueue** [comment] 2020-05-29 07:45
@citizen-seven  can you give a short way to reproduce? For example, if I do `SELECT foo FROM phanstasytable` as a SQL query, the error message will show enough detail. What kind of query are you doing? Thanks!

**Comment by citizen-seven** [comment] 2020-06-01 13:50
For example, `select a from b`. When there is no `b` table at all.

```
ClickHouse exception, code: 60, host: HOST, port: PORT
```

Metabase 0.34.3

**Comment by citizen-seven** [comment] 2020-06-14 17:00
@enqueue any updates here?

**Comment by enqueue** [comment] 2020-06-16 10:53
@citizen-seven When I create such a query, I see the error message `Table mydatabase.bar doesn't exist`, see movie: 
![clickhouse_mb_53](https://user-images.githubusercontent.com/5407006/84766015-69203c00-afd0-11ea-8802-6b51e7184713.gif)

How is your workflow different?

**Comment by StephenSorriaux** [comment] 2020-06-16 13:51
Hey there,

Just giving some information about this issue since I also got it:

![image](https://user-images.githubusercontent.com/16797053/84782791-bdcfb100-afe8-11ea-8bee-48193609198c.png)

But:
- I am still using an old CH version (19.8...)
- I am using an old version of Metabase (0.33.6) thus an also old version of your (awesome) driver

Looking at your animation it seems to be fixed in newer version. Maybe @citizen-seven is in a similar situation?

**Closed** 2021-12-07 06:44 UTC
Labels: clarification
